version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "Infrastructure:"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    ignore:
      # ignore lcf as we track a specific branch (5.1-syntax_5.1), not master
      # the update-3rdparty.yml workflow handles this correctly
      - dependency-name: "3rdparty/lcf"
    commit-message:
      prefix: "Infrastructure:"
